### ISSUE TITLE
Images not stacked though log says succes?

### ISSUE THREAD

**Issue by 7IM3rW** [tenekev/immich-auto-stack#17]
Hi There,

I used your tool today with the default settings to stack Canon Raws to their jpgs. In the Log it says success (yes dry run is false) but the images appear to not be stacked even after restart of immich container.

Is there something i am missing?

Thank you for your work!

docker compose:

```
immich-auto-stack:
    container_name: immich-auto-stack
    image: ghcr.io/tenekev/immich-auto-stack:latest
    restart: unless-stopped
    networks:
        - immich
    environment:

      # This is default. Can be omitted.
      API_URL: http://immich_server:3001/api

      # https://immich.app/docs/features/command-line-interface#obtain-the-api-key
      API_KEY: redacted

      # This is default. Can be omitted. When true, prints output but does not submit any changes
      DRY_RUN: False

      # Whether or not to modify photos that are already in stacks. Going over all assets takes a lot more time.
      SKIP_PREVIOUS: True
```

Log

![Image](https://github.com/user-attachments/assets/3ae1096c-8541-4e43-8801-34ab92ca5c25)

Immich:

![Image](https://github.com/user-attachments/assets/3afaa10c-b24b-4b5b-9dcb-86ea79ae03ea)

https://github.com/user-attachments/assets/d4372a22-d77f-4f2f-8c2f-aa1d59f72eaf
